#!/bin/sh

#killall -q sh;

Dir="$HOME/dwm_config/scripts/status-bar";

# UP="$(pacman -Qu | grep -Fcv "[ignored]")"; # Updates
# BAT="$(acpi)"

# Initialize Laptop Screen and Extra Monitor
xrandr --output LVDS1 --brightness 0.4
xrandr --output VGA1 --mode 1366x768 --rate 59.86 --right-of LVDS1;

# Initialize Desktops (For g0d-bin)
#xrandr --output DP-0    --mode 1920x1080 --rate 144;
#xrandr --output HDMI-0  --mode 1920x1080 --rate 59 --right-of DP-0;
#xrandr --output DVI-D-0 --mode 1920x1080 --rate 60 --left-of DP-0;

# Wallpapers
feh --recursive --randomize --bg-fill ~/Pictures/Wallpaper/;

#Keyboard LED's
#g513-led -p /home/danny/AUR/g513/profiles/ran-slate;

#Screenshot Software
flameshot;


drawTopbar(){                # Draws Top bar script widgets
  cd "$Dir"/ ;
  ./realtime &          # Displays date and time (date)
  #sh "$Dir/weather.sh"       #
  #sh "$Dir/update.sh"        # Displays # of upgradeable packages ()
  #sh "$Dir/mail.sh"          # Checks Inbox for Unread
  #sh "$Dir/vpn.sh"           # Checks Status of VPN (protonvpn status)
}

#drawBotbar(){                 # Draws Bottom bar script widgets
#  #sh "$Dir/cpu.sh"           #
#  #sh "$Dir/ram.sh"           #
#  #sh "$Dir/network.sh"       #
#  #sh "$Dir/disks.sh"         #
#}

isRunning(){
ps -C realtime.sh -o pid =
}

drawTopbar
